version: "3"
name: finance.ai

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=finance.ai
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
